import Female1 from "../images/VRC image F1.png";
import Female2 from "../images/VRC image F2.png";
import Female3 from "../images/VRC image F3.png";
import Female4 from "../images/VRC image F4.png";
import Female5 from "../images/VRC image F5.png";
import Female6 from "../images/VRC image F6.png";
import Female7 from "../images/VRC image F7.png";
import Female8 from "../images/VRC image F8.png";
import Female9 from "../images/VRC image F9.png";
import Female10 from "../images/VRC image F10.png";
import Female11 from "../images/VRC image F11.png";
import Female12 from "../images/VRC image F12.png";
import Female13 from "../images/VRC image F13.png";
import Female14 from "../images/VRC image F14.png";
import Female15 from "../images/VRC image F15.png";
import Female16 from "../images/VRC image F16.png";
import Female17 from "../images/VRC image F17.png";
import Female18 from "../images/VRC image F18.png";
import Female19 from "../images/VRC image F19.png";

import Male1 from "../images/VRC image M1.png";
import Male2 from "../images/VRC image M2.png";
import Male3 from "../images/VRC image M3.png";
import Male4 from "../images/VRC image M4.png";
import Male5 from "../images/VRC image M5.png";
import Avatar from "@mui/material/Avatar";

export const data = [
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Female15,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Female16,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female17,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female18,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male4,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Female19,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female13,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female12,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Male3,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Female2,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male4,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female2,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male5,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male4,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female4,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Female5,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Female6,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female7,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Male5,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female8,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Female9,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Female10,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female11,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male4,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male5,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female13,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female12,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male2,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Female14,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female15,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
  {
    id: 1,
    name: "Doe",
    designation: "Full stack developer",
    image: Male2,
    phone: "+455837837438",
    email: "ere@.gmail.com",
    status: "inactive",
    join: "2/02/22",
  },
  {
    id: 1,
    name: "Marry",
    designation: "Graphics designer",
    image: Female3,
    phone: "+15837837438",
    email: "marry@.gmail.com",
    status: "active",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "Leo",
    designation: "Graphics designer",
    image: Female1,
    phone: "+15837837438",
    email: "leo@.gmail.com",
    status: "reassigned",
    join: "24/02/22",
  },
  {
    id: 1,
    name: "John",
    designation: "Frontend developer",
    image: Male1,
    phone: "+983837837438",
    email: "dfkhsdj@.gmail.com",
    status: "active",
    join: "6/08/22",
  },
];

export const columnData = [
  {
    id: "name",
    Header: "Name",
    accessor: "name",
    Cell: ({ row }: any) => {
      return (
        <div className="flex items-center text-left gap-3">
          <Avatar
            src={row?.original?.image}
            sx={{
              width: "50px !important",
              height: "50px !important",
            }}
          >
            {row.original?.name}
          </Avatar>
          <div className="flex flex-col">
            <span>{row.original?.name}</span>
            <span className="text-xs">{row.original?.designation}</span>
          </div>
        </div>
      );
    },
    width: 250,
  },

  {
    id: "email",
    Header: "Email",
    accessor: "email",
    Cell: ({ value }: any) => {
      return <span className="opacity-70">{value}</span>;
    },
    width: 200,
  },
  {
    id: "phone",
    Header: "Phone",
    accessor: "phone",
    Cell: ({ value }: any) => {
      return <span className="opacity-70">{value}</span>;
    },
    width: 200,
  },
  {
    id: "date",
    Header: "Joining Date",
    accessor: "join",
    Cell: ({ value }: any) => {
      return <span className="opacity-70">{value}</span>;
    },
    width: 200,
  },
  {
    id: "status",
    Header: "Status",
    accessor: "status",
    Cell: ({ value }: any) => {
      return (
        <div className="capitalize text-sm">
          {value === "active" ? (
            <span className="bg-green-200 text-green-600 px-3 pb-[3px] rounded-md">
              {value}
            </span>
          ) : value === "inactive" ? (
            <span className="bg-red-100 text-red-600 px-3 pb-[3px] rounded-md">
              {value}
            </span>
          ) : (
            <span className="bg-yellow-100 text-yellow-600 px-3 pb-[3px] rounded-md">
              {value}
            </span>
          )}
        </div>
      );
    },
    width: 200,
  },
];
